---
#
# Install an NFSv4 server
#

- name: Load distribution-specific parameters
  include_tasks: 'init-{{ansible_os_family}}.yml'
  tags:
    - nfs
    - nfs-server

- name: disable module blacklisting (Rocky Linux 8 in STFC Cloud)
  file:
    path: /etc/modprobe.d/quattor.conf
    state: absent
  register: result
  when: is_rocky_8

- name: reboot if module blacklist disabled for first time (Rocky Linux 8 in STFC Cloud)
  reboot:
    reboot_timeout: 600
  when: 
    - is_rocky_8
    - result.changed

- name: install NFS server software
  tags:
    - nfs
    - nfs-server
  package:
    pkg: '{{nfs_server_packages}}'
    state: '{{ pkg_install_state }}'

- name: Ensure export directories exist
  tags:
    - nfs
    - nfs-server
  file:
    path: "{{item.path}}"
    state: directory
  loop: '{{NFS_EXPORTS}}'

- name: Export directories
  tags:
    - nfs
    - nfs-server
  lineinfile:
    dest: '/etc/exports'
    create: yes
    backup: yes
    line: '{{item.path}} {% for client in item.clients %}{{client}}({{item.options|default("async,rw,no_root_squash,no_subtree_check,crossmnt")}}) {% endfor %}'
    regexp: '^ *{{item.path}} +'
    state: present
  loop: '{{NFS_EXPORTS}}'

- name: Ensure portmapper is running
  tags:
    - nfs
    - nfs-server
  service:
    name: 'rpcbind'
    enabled: yes
    state: 'started'

- name: Ensure NFS server is running (Debian 8 "jessie")
  tags:
    - nfs
    - nfs-server
  command: |
     env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin _SYSTEMCTL_SKIP_REDIRECT=true /etc/init.d/nfs-kernel-server start
  args:
    chdir: '/'
  when: 'is_debian_8'

- name: Ensure NFS server is running
  tags:
    - nfs
    - nfs-server
  systemd:
    name: '{{item}}'
    enabled: yes
    state: '{{_nfs_server_started_state}}'
  loop: '{{nfs_server_services}}'
  when: 'not is_debian_8'

- name: Configure SELinux for NFS
  tags:
    - nfs
    - nfs-server
  seboolean:
    name: nfs_export_all_rw
    state: yes
    persistent: yes
  when: ansible_selinux.status == "enabled"

- name: Ensure nfsd module is loaded
  tags:
    - nfs
    - nfs-server
  modprobe:
    name: nfsd
    state: present

- name: Configure iptables for NFS
  tags:
    - nfs
    - nfs-server
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
    comment: "Allow NFS {{ item.name }}"
  loop:
    - { name: "Portmapper", protocol: tcp, port: "111" }
    - { name: "Portmapper", protocol: udp, port: "111" }
    - { name: "NFS", protocol: tcp, port: "2049" }
    - { name: "NFS", protocol: udp, port: "2049" }
    - { name: "NFSv3 mountd", protocol: tcp, port: "20048" }
    - { name: "NFSv3 mountd", protocol: udp, port: "20048" }
  when: ansible_os_family == "RedHat"

- name: Ensure iptables is running
  tags:
    - nfs
    - nfs-server
  service:
    name: iptables
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Reload NFS exports file
  tags:
    - nfs
    - nfs-server
  command:
    exportfs -r

