---
#
# Set variables for RHEL/CentOS variants
#

# install db4-utils on Rocky 8
- name: Install db4-utils from Raven repository
  yum:
    name: db4-utils
    state: present
    enablerepo: raven
  when: is_rocky_8

- name: Set GridEngine master variables (RHEL/CentOS)
  tags:
    - gridengine
    - gridengine-master
  set_fact:
    # qmaster service name
    gridengine_master_service: 'sgemaster_{{SGE_CELL}}'
    # packages to install (the `inst_sge` script errors out unless *all* SGE
    # binaries are installed, hence `gridengine-execd` on the master node as
    # well)
    gridengine_master_packages:
      - gridengine-devel
      - gridengine-drmaa4ruby
      - gridengine-execd
      - gridengine-qmaster
      - gridengine-qmon
  when: is_rhel_compatible
